### PR TITLE
Update pm2 to latest version

### PR DESCRIPTION
**Pull request by matthew-white**
This PR updates pm2 to the latest version.

#### What has been done to verify that this works as intended?

I haven't done much to verify this change to the patch version. If there is an issue, then CircleCI or regression testing should help catch it.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/getodk/docs/issues/new) and include the link below.

No change needed.

#### Before submitting this PR, please make sure you have:

- [x] verified that any code or assets from external sources are properly credited in comments.

### CODE REVIEW

**Review by sadiqkhoja — APPROVED** [review]
It would be nice to verify that multiple instances of pm2 are running on dev/test environment

**Comment by matthew-white** [comment]
> It would be nice to verify that multiple instances of pm2 are running on dev/test environment

How have you done that in the past? Could we check for that in the `central` CircleCI?

**Comment by matthew-white** [comment]
I think I'm going to go ahead and merge. If we're going to verify this, I think it'd be best to do so in CircleCI. (This won't be the last time that we update pm2!) @sadiqkhoja, let me know if you have thoughts about how to do that!

**Comment by matthew-white** [comment]
From @sadiqkhoja: Go into the service container. There is a command related to pm2 that can be used to check this.

**Pull request merged**
