### PR TITLE
Update pyxform to v1.12.0 to support big-image

### LINKED ISSUE #349: Update pyxform-http for v2023.1

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #349

#### What has been done to verify that this works as intended?
Put on dev server, converted a form with `big-image`, verified it works as expected.

#### Why is this the best possible solution? Were any other approaches considered?
This updates to the latest version of https://github.com/getodk/pyxform-http which was updated to the latest version of https://github.com/xlsform/pyxform

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Risk of regression is isolated to pyxform entities and media functionality. Both were reviewed and were fairly simple changes so are low-risk.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/getodk/docs/issues/new) and include the link below.
https://github.com/getodk/docs/issues/1549

#### Before submitting this PR, please make sure you have:

- [x] verified that any code or assets from external sources are properly credited in comments.

### CODE REVIEW

**Review by yanokwa — APPROVED** [review]
LGTM

**Comment by matthew-white** [comment]
@lognaturel, would you mind rebasing on `next`? Or I'd be happy to merge `master` into `next` to get c691355a61e49da18403f34ea849ef24742d34de in there.

**Review by matthew-white — APPROVED** [review]
Huzzah!

**Comment by matthew-white** [comment]
Also, I didn't know it was possible to "dismiss" a review, that's interesting.

**Comment by lognaturel** [comment]
For release notes:
* Add `big-image` support

**Pull request merged**
