### PR TITLE
nginx: set security headers at root path

### LINKED ISSUE #303: HSTS: set Strict-Transport-Security header at root path
HTTP requests are forwarded to HTTPS, so should probably be using HSTS.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #303 

Similar changes for frontend dev @ https://github.com/getodk/central-frontend/pull/630

### CODE REVIEW

**Comment by alxndrsn** [comment]
I've tested https://github.com/getodk/central-frontend/pull/630, but not sure how to check this locally.  But FWIW it now passes CI.

**Review by matthew-white — APPROVED** [review]
This looks right to me! @alxndrsn is going to deploy this to the QA server or to dev and will verify the change there. @alxndrsn, let me know when things look ✅, and I'll go ahead and merge.

Another thing I've been wondering about is whether we should add more testing around our ops (not as part of this PR, but as a future goal). Right now CircleCI verifies that Central builds and loads, but that's the extent of our automated verification:

https://github.com/getodk/central/blob/63cfab894cd619a703a1a38a00756f864e58b42b/.circleci/config.yml#L17-L34

If we had ops testing, we could write tests that these headers are being added in all the places.

**Comment by alxndrsn** [comment]
@matthew-white looks like it's working :+1:

**Comment by alxndrsn** [comment]
@matthew-white this commit hasn't been merged to `master`; is that expected?

**Comment by matthew-white** [comment]
Yeah, the branches in this repository work a little differently from `central-backend` and `central-frontend`. In this repository, anything merged into the `master` branch ships immediately. I've cut a `release` branch (#310), and once we're ready to release, we'll merge that into `master`.

**Pull request merged**
