### PR TITLE
Ignore docker-compose.override.yml

### PR DESCRIPTION
**Pull request by alanivey**
Allow for overrides of docker-compose.yml without impacting git status.

### CODE REVIEW

**Comment by yanokwa** [comment]
@alanivey I'm curious, what are you typically overriding?

**Comment by alanivey** [comment]
Setting `logging` for each service to send logs to Amazon CloudWatch, and making all named and anonymous volumes bind mounts to local directories for a few reasons (ease of backing up and restoring, being able to down+up the containers without losing LE certs)

**Comment by yanokwa** [comment]
@alanivey Thanks for clarifying. I didn't know about `docker-compose.override.yml` and it's super helpful! If you come across Docker best-practices that would be broadly useful to bake into Central, please do file issues. 

@lognaturel This seems like a great change to me. It's a known [convention](https://docs.docker.com/compose/extends/#multiple-compose-files).

**Comment by lognaturel** [comment]
Thanks, @alanivey, this is great. I've also filed a follow-up docs issue: https://github.com/getodk/docs/issues/1616

**Pull request merged**
